version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
      - run:
          name: Back-end build
          command: |
             # Your code here
             cd backend
             npm install
             npm run build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
